name: dump
publish_to: none

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies: 
  capstone:
    path: ../lib/capstone-dart
  ffi: ^2.0.1
  path: ^1.8.2
  rw_analyzer:
    path: ../lib/rw_analyzer
  rw_yaml:
    path: ../lib/rw_yaml
  
dev_dependencies:
  lints: ^2.0.0
