name: rw_diff
publish_to: none

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies: 
  ansicolor: ^2.0.1
  args: ^2.4.0
  async: ^2.11.0
  collection: ^1.17.1
  dart_console: ^1.1.2
  ffi: ^2.0.1
  path: ^1.8.2
  pe_coff:
    path: ../lib/pe_coff
  rw_decomp:
    path: ../rw_decomp
  tuple: ^2.0.1
  watcher: ^1.1.0
  x86_analyzer:
    path: ../lib/x86_analyzer
  
dev_dependencies:
  lints: ^2.0.0
