name: rw_assets
publish_to: none

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies: 
  args: ^2.4.0
  charcode: ^1.3.1
  console_bars: ^1.2.0
  path: ^1.8.2
  
dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.1
