name: rw_assets
publish_to: none

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies: 
  args: ^2.4.0
  charcode: ^1.3.1
  image: ^4.1.7
  path: ^1.9.0
  
dev_dependencies:
  lints: ^3.0.0
  test: ^1.25.1
