set shell := ["powershell.exe", "-c"]

# list justfile recipes
@help:
    just --list -u

# recreate build.ninja
@configure:
    dart run ../tools/rw_mod/bin/configure.dart --decomp-root=../ --mod-root=./

# build new patched exe
[no-exit-message]
@build:
    ninja

# clean + build
[no-exit-message]
@rebuild:
    just clean
    just configure
    ninja

# clean build artifacts
@clean:
    if (Test-Path build -PathType Container) { Remove-Item build -Force -Recurse }
    if (Test-Path game\RealWar.exe -PathType Leaf) { Remove-Item game\RealWar.exe -Force }
    if (Test-Path build.ninja -PathType Leaf) { Remove-Item build.ninja -Force }
    if (Test-Path .ninja_log -PathType Leaf) { Remove-Item .ninja_log -Force }
    if (Test-Path .ninja_deps -PathType Leaf) { Remove-Item .ninja_deps -Force }

# run patched exe
[no-exit-message]
@run:
    cd game; ./RealWar.exe

# build + run
[no-exit-message]
@buildrun:
    just build
    just run

# rebuild + run
[no-exit-message]
@rebuildrun:
    just rebuild
    just run
