name: rw_decomp
publish_to: none

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies: 
  args: ^2.4.0
  collection: ^1.18.0
  crypto: ^3.0.2
  ffi: ^2.0.1
  path: ^1.9.0
  pe_coff:
    path: ../lib/pe_coff
  ninja_syntax:
    path: ../lib/ninja_syntax
  x86_analyzer:
    path: ../lib/x86_analyzer
  yaml: ^3.1.1
  tuple: ^2.0.2
  
dev_dependencies:
  lints: ^3.0.0
  test: ^1.25.1
