name: rw_decomp
publish_to: none

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies: 
  args: ^2.4.0
  crypto: ^3.0.2
  ffi: ^2.0.1
  path: ^1.8.2
  pe_coff:
    path: ../lib/pe_coff
  ninja_syntax:
    path: ../lib/ninja_syntax
  x86_analyzer:
    path: ../lib/x86_analyzer
  yaml: ^3.1.1
  
dev_dependencies:
  lints: ^2.0.0
  test: ^1.24.1
