name: rw_mod
publish_to: none

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies: 
  args: ^2.4.0
  crypto: ^3.0.2
  ffi: ^2.0.1
  path: ^1.8.2
  pe_coff:
    path: ../lib/pe_coff
  ninja_syntax:
    path: ../lib/ninja_syntax
  rw_decomp:
    path: ../rw_decomp
  x86_analyzer:
    path: ../lib/x86_analyzer
  yaml: ^3.1.1
  
dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.1
